# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arbaz Hussain - blog
email: info@arbazhussain.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arbazhussain.com" # the base hostname & protocol for your site
usernames:
  twitter: 
  github: 
  linkedin: 
  instagram: 

permalink: pretty

# Build settings
markdown: kramdown
timezone: "+0530"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax:  false
      social:   true
